'use client';

import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // ── Customer menu ──────────────────────────────────────────────
    restaurantTagline: 'Authentic Italian Cuisine',
    table: 'Table',
    staffLogin: 'Staff Login',
    loadingMenu: 'Loading menu…',
    starters: 'Starters', mains: 'Mains', desserts: 'Desserts', drinks: 'Drinks',
    addToOrder: 'Add to Order',
    contains: 'Contains',
    viewOrder: 'View Order',
    yourOrder: 'Your Order',
    backToMenu: '← Back to Menu',
    backToOrder: '← Back to Order',
    each: 'each',
    subtotal: 'Subtotal',
    total: 'Total',
    proceedToPayment: 'Proceed to Payment',
    payment: 'Payment',
    totalDue: 'Total due',
    payApplePay: 'Pay with Apple Pay',
    payCounter: 'Pay at Counter',
    paymentTerms: 'By placing your order you agree to our terms. All prices include applicable taxes.',
    orderConfirmed: 'Order Confirmed!',
    orderNumber: 'Order #',
    estimatedWait: 'Your food is being prepared. Estimated wait: 20–30 min.',
    backToMenuBtn: 'Back to Menu',
    cartEmpty: 'Your cart is empty.',
    cartEmptyHint: 'Add items from the menu.',
    reviewOrder: 'Review Order',
    items: 'items',
    // ── Admin auth ─────────────────────────────────────────────────
    adminTitle: 'Staff Portal',
    adminUsername: 'Username',
    adminPassword: 'Password',
    adminSignIn: 'Sign In',
    adminSigningIn: 'Signing in…',
    adminDemoHint: 'Demo: admin / admin123',
    adminInvalidCreds: 'Invalid username or password.',
    // ── Admin nav ──────────────────────────────────────────────────
    navDashboard: 'Dashboard',
    navLiveOrders: 'Live Orders',
    navReceipts: 'Receipts',
    navMenu: 'Menu',
    navUserPortal: 'User Portal',
    navLogout: 'Logout',
    navStaffPortal: 'Staff Portal',
    // ── Dashboard ─────────────────────────────────────────────────
    tabOverview: '📊 Overview',
    tabQR: '📱 Table QR Codes',
    periodToday: 'Today',
    periodWeek: 'This Week',
    periodMonth: 'This Month',
    statActiveOrders: 'Active Orders',
    statDeliveredToday: 'Delivered Today',
    statRevenue: 'Revenue',
    statAvgOrder: 'Avg Order',
    revenueOverview: 'Revenue Overview',
    mostOrdered: 'Most Ordered',
    loadingChart: 'Loading…',
    noRevenueData: 'No revenue data for this period.',
    noOrdersYet: 'No orders yet.',
    // ── Live orders ───────────────────────────────────────────────
    liveOrdersTitle: 'Live Orders',
    refreshNote: 'Refreshes every 5s',
    filterAll: 'All',
    filterPending: 'Pending',
    filterInProgress: 'In Progress',
    filterDelivered: 'Delivered',
    loadingOrders: 'Loading orders…',
    noOrdersFound: 'No orders found.',
    markInProgress: 'Mark In Progress →',
    markDelivered: 'Mark Delivered ✓',
    backToPending: '← Pending',
    backToInProgressBtn: '← In Progress',
    doneBadge: '✓ Done',
    statusPending: 'Pending',
    statusInProgress: 'In Progress',
    statusDelivered: 'Delivered',
    statusCancelled: 'Cancelled',
    payApplePayLabel: '🍎 Apple Pay',
    payCounterLabel: '💵 Counter',
    // ── Menu management ───────────────────────────────────────────
    menuMgmtTitle: 'Menu Management',
    addItemBtn: '+ Add Item',
    colName: 'Name',
    colCategory: 'Category',
    colPrice: 'Price',
    colStatus: 'Status',
    colActions: 'Actions',
    colOrders: 'Orders',
    statusActive: 'Active',
    statusHidden: 'Hidden',
    editBtn: 'Edit',
    deleteBtn: 'Delete',
    deleteConfirm: 'Delete this menu item?',
    modalEditTitle: 'Edit Item',
    modalNewTitle: 'New Menu Item',
    fieldName: 'Name',
    fieldDescription: 'Description',
    fieldImageUrl: 'Image URL (optional)',
    fieldPrice: 'Price ($)',
    fieldCategory: 'Category',
    fieldAllergens: 'Allergens (comma-separated)',
    fieldAllergensPlaceholder: 'e.g. Gluten, Dairy, Nuts',
    fieldAvailable: 'Available on menu',
    saveChanges: 'Save Changes',
    cancelBtn: 'Cancel',
    // ── Receipts ──────────────────────────────────────────────────
    receiptsTitle: 'Receipts',
    printSelected: 'Print Selected',
    printAll: 'Print All',
    selectAll: 'Select all',
    loadingReceipts: 'Loading receipts…',
    noReceipts: 'No receipts yet.',
    printBtn: '🖨️ Print',
    receiptOrder: 'Order',
    receiptDate: 'Date',
    receiptPayment: 'Payment',
    receiptTotal: 'Total',
    receiptThankYou: 'Thank you for dining with us!',
    receiptSubtitle: 'Authentic Italian Cuisine',
    // ── QR Codes ──────────────────────────────────────────────────
    qrTitle: 'Table QR Codes',
    qrSubtitle: 'Customers scan these to open the menu on their table',
    qrSiteUrl: 'Site URL:',
    qrPrintAll: '🖨️ Print All',
    qrTable: 'Table',
    // ── Footer ────────────────────────────────────────────────────
    footerPoweredBy: 'Powered by',
    footerBrand: 'CC Enterprises Software',
  },

  es: {
    // ── Customer menu ──────────────────────────────────────────────
    restaurantTagline: 'Auténtica Cocina Italiana',
    table: 'Mesa',
    staffLogin: 'Acceso Personal',
    loadingMenu: 'Cargando menú…',
    starters: 'Entrantes', mains: 'Platos Principales', desserts: 'Postres', drinks: 'Bebidas',
    addToOrder: 'Añadir',
    contains: 'Contiene',
    viewOrder: 'Ver Pedido',
    yourOrder: 'Tu Pedido',
    backToMenu: '← Volver al Menú',
    backToOrder: '← Volver al Pedido',
    each: 'c/u',
    subtotal: 'Subtotal',
    total: 'Total',
    proceedToPayment: 'Ir al Pago',
    payment: 'Pago',
    totalDue: 'Total a pagar',
    payApplePay: 'Pagar con Apple Pay',
    payCounter: 'Pagar en Caja',
    paymentTerms: 'Al realizar tu pedido aceptas nuestros términos. Los precios incluyen impuestos.',
    orderConfirmed: '¡Pedido Confirmado!',
    orderNumber: 'Pedido #',
    estimatedWait: 'Tu comida está siendo preparada. Tiempo estimado: 20–30 min.',
    backToMenuBtn: 'Volver al Menú',
    cartEmpty: 'Tu carrito está vacío.',
    cartEmptyHint: 'Agrega productos desde el menú.',
    reviewOrder: 'Revisar Pedido',
    items: 'productos',
    // ── Admin auth ─────────────────────────────────────────────────
    adminTitle: 'Portal de Personal',
    adminUsername: 'Usuario',
    adminPassword: 'Contraseña',
    adminSignIn: 'Iniciar Sesión',
    adminSigningIn: 'Iniciando…',
    adminDemoHint: 'Demo: admin / admin123',
    adminInvalidCreds: 'Usuario o contraseña incorrectos.',
    // ── Admin nav ──────────────────────────────────────────────────
    navDashboard: 'Panel',
    navLiveOrders: 'Pedidos en Vivo',
    navReceipts: 'Recibos',
    navMenu: 'Menú',
    navUserPortal: 'Portal Cliente',
    navLogout: 'Cerrar Sesión',
    navStaffPortal: 'Portal de Personal',
    // ── Dashboard ─────────────────────────────────────────────────
    tabOverview: '📊 Resumen',
    tabQR: '📱 Códigos QR de Mesas',
    periodToday: 'Hoy',
    periodWeek: 'Esta Semana',
    periodMonth: 'Este Mes',
    statActiveOrders: 'Pedidos Activos',
    statDeliveredToday: 'Entregados Hoy',
    statRevenue: 'Ingresos',
    statAvgOrder: 'Pedido Promedio',
    revenueOverview: 'Resumen de Ingresos',
    mostOrdered: 'Más Pedidos',
    loadingChart: 'Cargando…',
    noRevenueData: 'Sin datos de ingresos para este período.',
    noOrdersYet: 'Sin pedidos aún.',
    // ── Live orders ───────────────────────────────────────────────
    liveOrdersTitle: 'Pedidos en Vivo',
    refreshNote: 'Actualiza cada 5s',
    filterAll: 'Todos',
    filterPending: 'Pendiente',
    filterInProgress: 'En Proceso',
    filterDelivered: 'Entregado',
    loadingOrders: 'Cargando pedidos…',
    noOrdersFound: 'No se encontraron pedidos.',
    markInProgress: 'Marcar En Proceso →',
    markDelivered: 'Marcar Entregado ✓',
    backToPending: '← Pendiente',
    backToInProgressBtn: '← En Proceso',
    doneBadge: '✓ Listo',
    statusPending: 'Pendiente',
    statusInProgress: 'En Proceso',
    statusDelivered: 'Entregado',
    statusCancelled: 'Cancelado',
    payApplePayLabel: '🍎 Apple Pay',
    payCounterLabel: '💵 Caja',
    // ── Menu management ───────────────────────────────────────────
    menuMgmtTitle: 'Gestión del Menú',
    addItemBtn: '+ Agregar Plato',
    colName: 'Nombre',
    colCategory: 'Categoría',
    colPrice: 'Precio',
    colStatus: 'Estado',
    colActions: 'Acciones',
    colOrders: 'Pedidos',
    statusActive: 'Activo',
    statusHidden: 'Oculto',
    editBtn: 'Editar',
    deleteBtn: 'Eliminar',
    deleteConfirm: '¿Eliminar este plato del menú?',
    modalEditTitle: 'Editar Plato',
    modalNewTitle: 'Nuevo Plato',
    fieldName: 'Nombre',
    fieldDescription: 'Descripción',
    fieldImageUrl: 'URL de Imagen (opcional)',
    fieldPrice: 'Precio ($)',
    fieldCategory: 'Categoría',
    fieldAllergens: 'Alérgenos (separados por coma)',
    fieldAllergensPlaceholder: 'ej. Gluten, Lácteos, Frutos secos',
    fieldAvailable: 'Disponible en el menú',
    saveChanges: 'Guardar Cambios',
    cancelBtn: 'Cancelar',
    // ── Receipts ──────────────────────────────────────────────────
    receiptsTitle: 'Recibos',
    printSelected: 'Imprimir Seleccionados',
    printAll: 'Imprimir Todo',
    selectAll: 'Seleccionar todo',
    loadingReceipts: 'Cargando recibos…',
    noReceipts: 'Sin recibos aún.',
    printBtn: '🖨️ Imprimir',
    receiptOrder: 'Pedido',
    receiptDate: 'Fecha',
    receiptPayment: 'Pago',
    receiptTotal: 'Total',
    receiptThankYou: '¡Gracias por visitarnos!',
    receiptSubtitle: 'Auténtica Cocina Italiana',
    // ── QR Codes ──────────────────────────────────────────────────
    qrTitle: 'Códigos QR de Mesas',
    qrSubtitle: 'Los clientes escanean esto para abrir el menú en su mesa',
    qrSiteUrl: 'URL del sitio:',
    qrPrintAll: '🖨️ Imprimir Todo',
    qrTable: 'Mesa',
    // ── Footer ────────────────────────────────────────────────────
    footerPoweredBy: 'Desarrollado por',
    footerBrand: 'CC Enterprises Software',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] ?? key;
  const toggle = () => setLang((l) => (l === 'en' ? 'es' : 'en'));
  return (
    <LanguageContext.Provider value={{ lang, t, toggle }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
