export const menuItems = [
  { id: 'm1', name: 'Bruschetta al Pomodoro', description: 'Toasted sourdough topped with fresh Roma tomatoes, basil, garlic, and extra-virgin olive oil.', price: 8.50, category: 'STARTERS', image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=400&q=80', allergens: ['Gluten'], available: true },
  { id: 'm2', name: 'Calamari Fritti', description: 'Lightly battered and fried squid rings served with marinara sauce and a wedge of lemon.', price: 13.00, category: 'STARTERS', image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&q=80', allergens: ['Gluten', 'Shellfish'], available: true },
  { id: 'm3', name: 'Caprese Classica', description: 'Buffalo mozzarella, vine-ripened tomatoes, fresh basil, aged balsamic glaze, and sea salt.', price: 11.00, category: 'STARTERS', image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=400&q=80', allergens: ['Dairy'], available: true },
  { id: 'm4', name: 'Zuppa del Giorno', description: "Chef's daily soup made from seasonal vegetables with a slice of rustic bread.", price: 7.50, category: 'STARTERS', image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80', allergens: ['Gluten'], available: true },
  { id: 'm5', name: 'Spaghetti alla Carbonara', description: 'Spaghetti with guanciale, Pecorino Romano, egg yolk, and freshly cracked black pepper.', price: 17.50, category: 'MAINS', image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&q=80', allergens: ['Gluten', 'Eggs', 'Dairy'], available: true },
  { id: 'm6', name: 'Pizza Margherita', description: 'Neapolitan pizza with San Marzano tomato sauce, fior di latte mozzarella, and fresh basil.', price: 15.00, category: 'MAINS', image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80', allergens: ['Gluten', 'Dairy'], available: true },
  { id: 'm7', name: 'Lasagna della Nonna', description: 'Slow-cooked Bolognese ragù layered with fresh pasta sheets, béchamel, and Parmigiano.', price: 18.50, category: 'MAINS', image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400&q=80', allergens: ['Gluten', 'Dairy', 'Eggs'], available: true },
  { id: 'm8', name: 'Risotto ai Funghi', description: 'Arborio rice with wild porcini and cremini mushrooms, white wine, Parmigiano, and truffle oil.', price: 19.00, category: 'MAINS', image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&q=80', allergens: ['Dairy'], available: true },
  { id: 'm9', name: 'Branzino al Forno', description: 'Oven-roasted sea bass with capers, olives, cherry tomatoes, white wine, and rosemary.', price: 24.00, category: 'MAINS', image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&q=80', allergens: ['Fish'], available: true },
  { id: 'm10', name: 'Pollo alla Parmigiana', description: 'Breaded chicken breast topped with tomato sauce, melted mozzarella, and Parmigiano.', price: 21.00, category: 'MAINS', image: 'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=400&q=80', allergens: ['Gluten', 'Dairy', 'Eggs'], available: true },
  { id: 'm11', name: 'Tiramisù', description: 'Classic Italian dessert with mascarpone cream, espresso-soaked ladyfingers, and cocoa powder.', price: 7.50, category: 'DESSERTS', image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80', allergens: ['Gluten', 'Dairy', 'Eggs'], available: true },
  { id: 'm12', name: 'Panna Cotta', description: 'Silky vanilla panna cotta served with a wild berry coulis.', price: 6.50, category: 'DESSERTS', image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80', allergens: ['Dairy'], available: true },
  { id: 'm13', name: 'Cannoli Siciliani', description: 'Crispy pastry shells filled with sweetened ricotta, chocolate chips, and candied orange peel.', price: 8.00, category: 'DESSERTS', image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80', allergens: ['Gluten', 'Dairy'], available: true },
  { id: 'm14', name: 'Gelato Artigianale', description: 'Two scoops of house-made artisan gelato — pistachio, stracciatella, or lemon sorbet.', price: 6.00, category: 'DESSERTS', image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400&q=80', allergens: ['Dairy'], available: true },
  { id: 'm15', name: 'Acqua Minerale', description: 'Still or sparkling mineral water — 750 ml bottle.', price: 3.50, category: 'DRINKS', image: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400&q=80', allergens: [], available: true },
  { id: 'm16', name: 'Vino della Casa', description: 'House wine — select red, white, or rosé. Served by the glass (200 ml).', price: 6.50, category: 'DRINKS', image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80', allergens: ['Sulphites'], available: true },
  { id: 'm17', name: 'Espresso', description: 'Short, intense Italian espresso made with our signature blend of Arabica beans.', price: 3.00, category: 'DRINKS', image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400&q=80', allergens: [], available: true },
  { id: 'm18', name: 'Limoncello', description: 'Authentic Amalfi limoncello served ice-cold in a chilled glass.', price: 5.50, category: 'DRINKS', image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80', allergens: [], available: true },
  { id: 'm19', name: 'Aperol Spritz', description: 'Classic Italian aperitif with Aperol, Prosecco, a splash of soda, and an orange slice.', price: 8.00, category: 'DRINKS', image: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=400&q=80', allergens: ['Sulphites'], available: true },
  { id: 'm20', name: 'Burrata con Prosciutto', description: 'Creamy burrata cheese over a bed of arugula, draped with thin slices of San Daniele prosciutto and a drizzle of honey.', price: 14.50, category: 'STARTERS', image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=400&q=80', allergens: ['Dairy'], available: true },
  { id: 'm21', name: 'Tagliatelle al Tartufo', description: 'Fresh egg tagliatelle tossed in a black truffle and Parmigiano cream sauce, finished with shaved summer truffle.', price: 26.00, category: 'MAINS', image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&q=80', allergens: ['Gluten', 'Eggs', 'Dairy'], available: true },
  { id: 'm22', name: 'Torta della Nonna', description: 'Traditional Italian custard tart with a buttery shortcrust shell, lemon pastry cream, and toasted pine nuts.', price: 7.00, category: 'DESSERTS', image: 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=400&q=80', allergens: ['Gluten', 'Dairy', 'Eggs', 'Nuts'], available: true },
  { id: 'm23', name: 'Negroni', description: 'The iconic Italian cocktail — Campari, sweet vermouth, and gin, stirred and served over ice with an orange peel.', price: 9.50, category: 'DRINKS', image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400&q=80', allergens: [], available: true },
];

export const demoOrders = [
  {
    id: 'demo001abc',
    tableId: '3',
    status: 'IN_PROGRESS',
    paymentMethod: 'APPLE_PAY',
    total: 46.00,
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: 'oi1', menuItemId: 'm6',  quantity: 2, specialInstructions: null,              price: 15.00, menuItem: { name: 'Pizza Margherita',    price: 15.00 } },
      { id: 'oi2', menuItemId: 'm16', quantity: 2, specialInstructions: null,              price: 6.50,  menuItem: { name: 'Vino della Casa',      price: 6.50  } },
      { id: 'oi3', menuItemId: 'm17', quantity: 1, specialInstructions: null,              price: 3.00,  menuItem: { name: 'Espresso',             price: 3.00  } },
    ],
  },
  {
    id: 'demo002def',
    tableId: '1',
    status: 'PENDING',
    paymentMethod: 'COUNTER',
    total: 55.50,
    createdAt: new Date(Date.now() - 3 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: 'oi4', menuItemId: 'm1',  quantity: 2, specialInstructions: 'No garlic please', price: 8.50,  menuItem: { name: 'Bruschetta al Pomodoro', price: 8.50  } },
      { id: 'oi5', menuItemId: 'm8',  quantity: 1, specialInstructions: null,                price: 19.00, menuItem: { name: 'Risotto ai Funghi',      price: 19.00 } },
      { id: 'oi6', menuItemId: 'm11', quantity: 1, specialInstructions: null,                price: 7.50,  menuItem: { name: 'Tiramisù',               price: 7.50  } },
      { id: 'oi7', menuItemId: 'm16', quantity: 2, specialInstructions: null,                price: 6.50,  menuItem: { name: 'Vino della Casa',         price: 6.50  } },
    ],
  },
  {
    id: 'demo003ghi',
    tableId: '7',
    status: 'DELIVERED',
    paymentMethod: 'APPLE_PAY',
    total: 38.00,
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: 'oi8',  menuItemId: 'm5',  quantity: 1, specialInstructions: null, price: 17.50, menuItem: { name: 'Spaghetti alla Carbonara', price: 17.50 } },
      { id: 'oi9',  menuItemId: 'm12', quantity: 1, specialInstructions: null, price: 6.50,  menuItem: { name: 'Panna Cotta',              price: 6.50  } },
      { id: 'oi10', menuItemId: 'm15', quantity: 2, specialInstructions: null, price: 3.50,  menuItem: { name: 'Acqua Minerale',           price: 3.50  } },
      { id: 'oi11', menuItemId: 'm17', quantity: 2, specialInstructions: null, price: 3.00,  menuItem: { name: 'Espresso',                 price: 3.00  } },
    ],
  },
  {
    id: 'demo004jkl',
    tableId: '5',
    status: 'PENDING',
    paymentMethod: 'APPLE_PAY',
    total: 62.00,
    createdAt: new Date(Date.now() - 1 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: 'oi12', menuItemId: 'm21', quantity: 1, specialInstructions: 'Extra truffle please', price: 26.00, menuItem: { name: 'Tagliatelle al Tartufo',   price: 26.00 } },
      { id: 'oi13', menuItemId: 'm9',  quantity: 1, specialInstructions: null,                   price: 24.00, menuItem: { name: 'Branzino al Forno',         price: 24.00 } },
      { id: 'oi14', menuItemId: 'm19', quantity: 1, specialInstructions: null,                   price: 8.00,  menuItem: { name: 'Aperol Spritz',             price: 8.00  } },
      { id: 'oi15', menuItemId: 'm15', quantity: 1, specialInstructions: null,                   price: 3.50,  menuItem: { name: 'Acqua Minerale',            price: 3.50  } },
    ],
  },
  {
    id: 'demo005mno',
    tableId: '2',
    status: 'IN_PROGRESS',
    paymentMethod: 'COUNTER',
    total: 43.00,
    createdAt: new Date(Date.now() - 8 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: 'oi16', menuItemId: 'm2',  quantity: 1, specialInstructions: null,         price: 13.00, menuItem: { name: 'Calamari Fritti',     price: 13.00 } },
      { id: 'oi17', menuItemId: 'm7',  quantity: 1, specialInstructions: null,         price: 18.50, menuItem: { name: 'Lasagna della Nonna', price: 18.50 } },
      { id: 'oi18', menuItemId: 'm13', quantity: 1, specialInstructions: null,         price: 8.00,  menuItem: { name: 'Cannoli Siciliani',   price: 8.00  } },
      { id: 'oi19', menuItemId: 'm23', quantity: 1, specialInstructions: 'On the rocks', price: 9.50, menuItem: { name: 'Negroni',             price: 9.50  } },
    ],
  },
  {
    id: 'demo006pqr',
    tableId: '9',
    status: 'PENDING',
    paymentMethod: 'COUNTER',
    total: 34.50,
    createdAt: new Date(Date.now() - 2 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: 'oi20', menuItemId: 'm3',  quantity: 1, specialInstructions: null, price: 11.00, menuItem: { name: 'Caprese Classica',  price: 11.00 } },
      { id: 'oi21', menuItemId: 'm10', quantity: 1, specialInstructions: null, price: 21.00, menuItem: { name: 'Pollo alla Parmigiana', price: 21.00 } },
      { id: 'oi22', menuItemId: 'm17', quantity: 1, specialInstructions: null, price: 3.00,  menuItem: { name: 'Espresso',           price: 3.00  } },
    ],
  },
  {
    id: 'demo007stu',
    tableId: '4',
    status: 'DELIVERED',
    paymentMethod: 'APPLE_PAY',
    total: 51.00,
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: 'oi23', menuItemId: 'm20', quantity: 1, specialInstructions: null, price: 14.50, menuItem: { name: 'Burrata con Prosciutto', price: 14.50 } },
      { id: 'oi24', menuItemId: 'm5',  quantity: 1, specialInstructions: null, price: 17.50, menuItem: { name: 'Spaghetti alla Carbonara', price: 17.50 } },
      { id: 'oi25', menuItemId: 'm11', quantity: 1, specialInstructions: null, price: 7.50,  menuItem: { name: 'Tiramisù',               price: 7.50  } },
      { id: 'oi26', menuItemId: 'm18', quantity: 2, specialInstructions: null, price: 5.50,  menuItem: { name: 'Limoncello',             price: 5.50  } },
    ],
  },
  {
    id: 'demo008vwx',
    tableId: '6',
    status: 'IN_PROGRESS',
    paymentMethod: 'APPLE_PAY',
    total: 29.50,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: 'oi27', menuItemId: 'm4',  quantity: 1, specialInstructions: null, price: 7.50,  menuItem: { name: 'Zuppa del Giorno', price: 7.50  } },
      { id: 'oi28', menuItemId: 'm8',  quantity: 1, specialInstructions: null, price: 19.00, menuItem: { name: 'Risotto ai Funghi', price: 19.00 } },
      { id: 'oi29', menuItemId: 'm15', quantity: 1, specialInstructions: null, price: 3.50,  menuItem: { name: 'Acqua Minerale',   price: 3.50  } },
    ],
  },
  {
    id: 'demo009yza',
    tableId: '11',
    status: 'PENDING',
    paymentMethod: 'COUNTER',
    total: 74.50,
    createdAt: new Date(Date.now() - 1 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: 'oi30', menuItemId: 'm20', quantity: 2, specialInstructions: null, price: 14.50, menuItem: { name: 'Burrata con Prosciutto',   price: 14.50 } },
      { id: 'oi31', menuItemId: 'm21', quantity: 1, specialInstructions: null, price: 26.00, menuItem: { name: 'Tagliatelle al Tartufo',   price: 26.00 } },
      { id: 'oi32', menuItemId: 'm22', quantity: 1, specialInstructions: null, price: 7.00,  menuItem: { name: 'Torta della Nonna',        price: 7.00  } },
      { id: 'oi33', menuItemId: 'm23', quantity: 1, specialInstructions: null, price: 9.50,  menuItem: { name: 'Negroni',                  price: 9.50  } },
    ],
  },
  {
    id: 'demo010bcd',
    tableId: '8',
    status: 'DELIVERED',
    paymentMethod: 'COUNTER',
    total: 40.00,
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: 'oi34', menuItemId: 'm2',  quantity: 1, specialInstructions: null, price: 13.00, menuItem: { name: 'Calamari Fritti',    price: 13.00 } },
      { id: 'oi35', menuItemId: 'm6',  quantity: 1, specialInstructions: null, price: 15.00, menuItem: { name: 'Pizza Margherita',   price: 15.00 } },
      { id: 'oi36', menuItemId: 'm14', quantity: 2, specialInstructions: null, price: 6.00,  menuItem: { name: 'Gelato Artigianale', price: 6.00  } },
    ],
  },
];

export const demoRevenue = {
  day:   { total: 487.50, count: 11, avg: 44.32, data: [{ label: '12:00', revenue: 62 }, { label: '13:00', revenue: 118 }, { label: '14:00', revenue: 95 }, { label: '19:00', revenue: 76 }, { label: '20:00', revenue: 136.50 }] },
  week:  { total: 3241.00, count: 74, avg: 43.80, data: [{ label: 'Mon', revenue: 412 }, { label: 'Tue', revenue: 389 }, { label: 'Wed', revenue: 501 }, { label: 'Thu', revenue: 478 }, { label: 'Fri', revenue: 612 }, { label: 'Sat', revenue: 849 }] },
  month: { total: 14820.00, count: 338, avg: 43.84, data: [{ label: 'Week 1', revenue: 3210 }, { label: 'Week 2', revenue: 3640 }, { label: 'Week 3', revenue: 3750 }, { label: 'Week 4', revenue: 4220 }] },
};

export const demoTopItems = [
  { rank: 1, id: 'm6',  name: 'Pizza Margherita',         category: 'MAINS',    price: 15.00, totalOrders: 142, revenue: 2130.00 },
  { rank: 2, id: 'm5',  name: 'Spaghetti alla Carbonara', category: 'MAINS',    price: 17.50, totalOrders: 98,  revenue: 1715.00 },
  { rank: 3, id: 'm11', name: 'Tiramisù',                 category: 'DESSERTS', price: 7.50,  totalOrders: 89,  revenue: 667.50  },
  { rank: 4, id: 'm8',  name: 'Risotto ai Funghi',        category: 'MAINS',    price: 19.00, totalOrders: 76,  revenue: 1444.00 },
  { rank: 5, id: 'm1',  name: 'Bruschetta al Pomodoro',   category: 'STARTERS', price: 8.50,  totalOrders: 71,  revenue: 603.50  },
];
